--- 
recorded_with: VCR 2.2.4
http_interactions: 
- request: 
    method: post
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments?name=Test&organization_id=ACME_Corporation&prior=1
    body: 
      string: "{\"environment\":{\"prior\":1,\"name\":\"Test\"}}"
    headers: 
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Authorization: 
      - OAuth oauth_body_hash="9KzQFg2PcGFImVLKB3ygN4CtBaU%3D", oauth_consumer_key="cloud_forms", oauth_nonce="lbgDllBeXQ3jQZedYbsrJBxmA8Y51DnHVZbIDYi0D9Q", oauth_signature="cGys7X6yBmKmPQMrCGGvY7OhMcs%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345056410", oauth_version="1.0"
      Content-Length: 
      - "41"
      Content-Type: 
      - application/json
      Accept: 
      - "*/*"
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Cache-Control: 
      - max-age=0, private, must-revalidate
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Date: 
      - Wed, 15 Aug 2012 18:46:49 GMT
      Transfer-Encoding: 
      - chunked
      Content-Type: 
      - application/json; charset=utf-8
      X-Runtime: 
      - "0.447849"
      Etag: 
      - "\"39e17ef95f3eeffc7b18f3dd342a2699\""
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":109,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-15T18:46:50Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-15T18:46:50Z\"}"
    http_version: 
  recorded_at: Wed, 15 Aug 2012 18:46:51 GMT
- request: 
    method: get
    uri: https://10.11.230.105/katello/api/environments/109
    body: 
      string: ""
    headers: 
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="XcopRswNmVGlMjWfyA5UaJQyRCUPRN63LUuXKp7PnRY", oauth_signature="sA2r1HzAcy4%2BCyxcDyrDaT9m7kU%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345056411", oauth_version="1.0"
      Accept: 
      - application/json
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Cache-Control: 
      - max-age=0, private, must-revalidate
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Date: 
      - Wed, 15 Aug 2012 18:46:50 GMT
      Transfer-Encoding: 
      - chunked
      Content-Type: 
      - application/json; charset=utf-8
      X-Runtime: 
      - "0.021295"
      Etag: 
      - "\"39e17ef95f3eeffc7b18f3dd342a2699\""
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":109,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-15T18:46:50Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-15T18:46:50Z\"}"
    http_version: 
  recorded_at: Wed, 15 Aug 2012 18:46:51 GMT
- request: 
    method: delete
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments/109
    body: 
      string: ""
    headers: 
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="5lf9zQhfQD19uhIoUdaWMFLiIOQtMv8n9YogUlw", oauth_signature="Zpk8mTp1sS%2BWnRjYElIU3F5XNYI%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345056411", oauth_version="1.0"
      Accept: 
      - application/json
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Cache-Control: 
      - max-age=0, private, must-revalidate
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Date: 
      - Wed, 15 Aug 2012 18:46:50 GMT
      Transfer-Encoding: 
      - chunked
      Content-Type: 
      - application/json; charset=utf-8
      X-Runtime: 
      - "0.144408"
      Etag: 
      - "\"c8c52277d7dc1e436b64c29445f95b07\""
    body: 
      string: Deleted environment '109'
    http_version: 
  recorded_at: Wed, 15 Aug 2012 18:46:51 GMT
