--- 
http_interactions: 
- request: 
    method: post
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments?name=Test&organization_id=ACME_Corporation&prior=1
    body: 
      string: "{\"environment\":{\"name\":\"Test\",\"prior\":1}}"
    headers: 
      Content-Type: 
      - application/json
      Content-Length: 
      - "41"
      User-Agent: 
      - OAuth gem v0.4.6
      Authorization: 
      - OAuth oauth_body_hash="lCe2lMYXISkHQNPzaGPJ0yiK97Y%3D", oauth_consumer_key="cloud_forms", oauth_nonce="vN6VaRqbN9CU2yviPK0zf7wx9cfQSBDP8C9dP5miso", oauth_signature="uztDzfdRo8Uhuc8tSKrPXZ14Lyk%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1343842700", oauth_version="1.0"
      Accept: 
      - "*/*"
      Http-Katello-User: 
      - admin
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Content-Type: 
      - application/json; charset=utf-8
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Transfer-Encoding: 
      - chunked
      Date: 
      - Wed, 22 Aug 2012 14:23:13 GMT
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Cache-Control: 
      - max-age=0, private, must-revalidate
      X-Runtime: 
      - "0.279111"
      Etag: 
      - "\"9d145af0c1b735ea1c23eb9a1fe68b42\""
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":197,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-22T14:23:13Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-22T14:23:13Z\"}"
    http_version: 
  recorded_at: Wed, 01 Aug 2012 17:38:20 GMT
- request: 
    method: get
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments
    body: 
      string: ""
    headers: 
      User-Agent: 
      - OAuth gem v0.4.6
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="bTYpDTlKbZMNdMbNQu27tlFmBkWKxTVVLlbJNIPWfM", oauth_signature="eGRiEkhvXZko2lGJu6KrXtXjgVM%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1343842700", oauth_version="1.0"
      Accept: 
      - application/json
      Http-Katello-User: 
      - admin
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Content-Type: 
      - application/json; charset=utf-8
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Transfer-Encoding: 
      - chunked
      Date: 
      - Wed, 22 Aug 2012 14:23:13 GMT
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Cache-Control: 
      - max-age=0, private, must-revalidate
      X-Runtime: 
      - "0.025600"
      Etag: 
      - "\"409f31a1e5dbe630a41c6ccc1ecf835b\""
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
    body: 
      string: "[{\"library\":true,\"prior\":null,\"id\":1,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-07-02T18:47:39Z\",\"name\":\"Library\",\"description\":null,\"prior_id\":null,\"created_at\":\"2012-07-02T18:47:39Z\"},{\"library\":false,\"prior\":\"Library\",\"id\":197,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-22T14:23:13Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-22T14:23:13Z\"}]"
    http_version: 
  recorded_at: Wed, 01 Aug 2012 17:38:20 GMT
- request: 
    method: delete
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments/197
    body: 
      string: ""
    headers: 
      User-Agent: 
      - OAuth gem v0.4.6
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="A4vL4Aq66t1BFk02hkplzTV4oEGEuNvelJ26bHdGk", oauth_signature="fgVOMsDhAU5R1UpY0mnKQkVDNnU%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1343842700", oauth_version="1.0"
      Accept: 
      - application/json
      Http-Katello-User: 
      - admin
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Content-Type: 
      - application/json; charset=utf-8
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Transfer-Encoding: 
      - chunked
      Date: 
      - Wed, 22 Aug 2012 14:23:14 GMT
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Cache-Control: 
      - max-age=0, private, must-revalidate
      X-Runtime: 
      - "0.137646"
      Etag: 
      - "\"67215211486103d70c52ffa1485edbdb\""
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
    body: 
      string: Deleted environment '197'
    http_version: 
  recorded_at: Wed, 01 Aug 2012 17:38:20 GMT
recorded_with: VCR 2.2.4
