--- 
http_interactions: 
- request: 
    method: post
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments?name=Test&organization_id=ACME_Corporation&prior=1
    body: 
      string: "{\"environment\":{\"name\":\"Test\",\"prior\":1}}"
    headers: 
      Content-Type: 
      - application/json
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Content-Length: 
      - "41"
      Accept: 
      - "*/*"
      Authorization: 
      - OAuth oauth_body_hash="lCe2lMYXISkHQNPzaGPJ0yiK97Y%3D", oauth_consumer_key="cloud_forms", oauth_nonce="Rmg68EQAfPKhYNu1fh9lDdM40S0zelLmW3EmDXO62Q", oauth_signature="tud%2BPtzBCyDs6cmMrboYXfdh%2FQk%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1343842700", oauth_version="1.0"
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Date: 
      - Tue, 14 Aug 2012 20:37:31 GMT
      Content-Type: 
      - application/json; charset=utf-8
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Etag: 
      - "\"c3605114ba61fd4e5acc9064c8020239\""
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      X-Runtime: 
      - "0.267708"
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Transfer-Encoding: 
      - chunked
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":90,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-14T20:37:31Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-14T20:37:31Z\"}"
    http_version: 
  recorded_at: Wed, 01 Aug 2012 17:38:20 GMT
- request: 
    method: get
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments
    body: 
      string: ""
    headers: 
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Accept: 
      - application/json
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="jj8ATGKuttgSLWMRHFc5mHDykJtVGwSOotpZ5EMrtY", oauth_signature="IFsL5%2BUNyu7zhzaBSylnvAFGi%2Fw%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1343842700", oauth_version="1.0"
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Date: 
      - Tue, 14 Aug 2012 20:37:31 GMT
      Content-Type: 
      - application/json; charset=utf-8
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Etag: 
      - "\"b28639b876854966bf20387f90b60daf\""
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      X-Runtime: 
      - "0.024243"
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Transfer-Encoding: 
      - chunked
    body: 
      string: "[{\"library\":true,\"prior\":null,\"id\":1,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-07-02T18:47:39Z\",\"name\":\"Library\",\"description\":null,\"prior_id\":null,\"created_at\":\"2012-07-02T18:47:39Z\"},{\"library\":false,\"prior\":\"Library\",\"id\":90,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-14T20:37:31Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-14T20:37:31Z\"}]"
    http_version: 
  recorded_at: Wed, 01 Aug 2012 17:38:20 GMT
- request: 
    method: delete
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments/90
    body: 
      string: ""
    headers: 
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Accept: 
      - application/json
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="0epzVRBhGZRou7XieBoxT7VGGJTOoHc4YWT4VGMLg", oauth_signature="S6LFnRWXMS6gwcxuUPjPxVg4QTE%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1343842700", oauth_version="1.0"
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Date: 
      - Tue, 14 Aug 2012 20:37:31 GMT
      Content-Type: 
      - application/json; charset=utf-8
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Etag: 
      - "\"118c8abf7ddce311b708eacb07da0962\""
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      X-Runtime: 
      - "0.260224"
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Transfer-Encoding: 
      - chunked
    body: 
      string: Deleted environment '90'
    http_version: 
  recorded_at: Wed, 01 Aug 2012 17:38:20 GMT
recorded_with: VCR 2.2.4
