--- 
recorded_with: VCR 2.2.4
http_interactions: 
- request: 
    method: post
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments?name=Test&organization_id=ACME_Corporation&prior=1
    body: 
      string: "{\"environment\":{\"prior\":1,\"name\":\"Test\"}}"
    headers: 
      Authorization: 
      - OAuth oauth_body_hash="9KzQFg2PcGFImVLKB3ygN4CtBaU%3D", oauth_consumer_key="cloud_forms", oauth_nonce="6rduptCv1s2qvyoDzB55Gnt8wmqyl9iMRWZTQiq8w", oauth_signature="nHVBCoJZE2H7t1CEou7Kw9%2BGp3w%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345484824", oauth_version="1.0"
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Accept: 
      - "*/*"
      Content-Length: 
      - "41"
      Content-Type: 
      - application/json
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Date: 
      - Mon, 20 Aug 2012 17:47:03 GMT
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Transfer-Encoding: 
      - chunked
      Content-Type: 
      - application/json; charset=utf-8
      Etag: 
      - "\"3a31c199bdcc358df462b68094a8805b\""
      X-Runtime: 
      - "0.282780"
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":154,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-20T17:47:03Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-20T17:47:03Z\"}"
    http_version: 
  recorded_at: Mon, 20 Aug 2012 17:47:04 GMT
- request: 
    method: get
    uri: https://10.11.230.105/katello/api/environments/154
    body: 
      string: ""
    headers: 
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="9YKo9nptUs4iPnHIBy4lNwU2htlkHpiaCorRLg7zU", oauth_signature="ScRNF%2Bs%2BLUDZ%2B6qJx6ft3dceqEg%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345484824", oauth_version="1.0"
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Accept: 
      - application/json
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Date: 
      - Mon, 20 Aug 2012 17:47:03 GMT
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Transfer-Encoding: 
      - chunked
      Content-Type: 
      - application/json; charset=utf-8
      Etag: 
      - "\"3a31c199bdcc358df462b68094a8805b\""
      X-Runtime: 
      - "0.143925"
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":154,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-20T17:47:03Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-20T17:47:03Z\"}"
    http_version: 
  recorded_at: Mon, 20 Aug 2012 17:47:04 GMT
- request: 
    method: delete
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments/154
    body: 
      string: ""
    headers: 
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="cyFEk9wW0khIq3kBwHyEVdjfDuTwzKrcdSnZQ3MIY", oauth_signature="ydH5LawydCvkI5cngR8jL8iLMZs%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345484824", oauth_version="1.0"
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Accept: 
      - application/json
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Date: 
      - Mon, 20 Aug 2012 17:47:04 GMT
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Transfer-Encoding: 
      - chunked
      Content-Type: 
      - application/json; charset=utf-8
      Etag: 
      - "\"849ec568a3148267eabe0f0894bc65a0\""
      X-Runtime: 
      - "0.144929"
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
    body: 
      string: Deleted environment '154'
    http_version: 
  recorded_at: Mon, 20 Aug 2012 17:47:05 GMT
