--- 
recorded_with: VCR 2.2.4
http_interactions: 
- request: 
    method: post
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments?name=Test&organization_id=ACME_Corporation&prior=1
    body: 
      string: "{\"environment\":{\"name\":\"Test\",\"prior\":1}}"
    headers: 
      Http-Katello-User: 
      - admin
      Content-Type: 
      - application/json
      Content-Length: 
      - "41"
      Authorization: 
      - OAuth oauth_body_hash="lCe2lMYXISkHQNPzaGPJ0yiK97Y%3D", oauth_consumer_key="cloud_forms", oauth_nonce="ZK1KOp7z5UrjzBHQ31PXvtfJHQ9VSlm5mssDUAKQ", oauth_signature="ZHuBqZ7pNA7E3GA364OIvEMsB1w%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345472382", oauth_version="1.0"
      Accept: 
      - "*/*"
      User-Agent: 
      - OAuth gem v0.4.6
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Etag: 
      - "\"5ce579f65f1b798ba797dbca6297a6e1\""
      Transfer-Encoding: 
      - chunked
      Content-Type: 
      - application/json; charset=utf-8
      Cache-Control: 
      - max-age=0, private, must-revalidate
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Date: 
      - Mon, 20 Aug 2012 14:19:41 GMT
      X-Runtime: 
      - "0.260248"
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":131,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-20T14:19:41Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-20T14:19:41Z\"}"
    http_version: 
  recorded_at: Mon, 20 Aug 2012 14:19:42 GMT
- request: 
    method: get
    uri: https://10.11.230.105/katello/api/environments/131
    body: 
      string: ""
    headers: 
      Http-Katello-User: 
      - admin
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="dPVQCV0t209YokJDajFkb3kaz8ZGPRBPVsYQWVQs", oauth_signature="LL%2BM%2BoCjUraoBS5qNC40PLkpM%2FY%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345472382", oauth_version="1.0"
      Accept: 
      - application/json
      User-Agent: 
      - OAuth gem v0.4.6
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Etag: 
      - "\"5ce579f65f1b798ba797dbca6297a6e1\""
      Transfer-Encoding: 
      - chunked
      Content-Type: 
      - application/json; charset=utf-8
      Cache-Control: 
      - max-age=0, private, must-revalidate
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Date: 
      - Mon, 20 Aug 2012 14:19:42 GMT
      X-Runtime: 
      - "0.141169"
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":131,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-20T14:19:41Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-20T14:19:41Z\"}"
    http_version: 
  recorded_at: Mon, 20 Aug 2012 14:19:43 GMT
- request: 
    method: delete
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments/131
    body: 
      string: ""
    headers: 
      Http-Katello-User: 
      - admin
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="F8IY0HsXWJhLr0ob3zybkKyYEpOn8uETxkpO1xGVUXE", oauth_signature="7Zjuum9RGKUc8VPYhNUa9V11EZc%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345472383", oauth_version="1.0"
      Accept: 
      - application/json
      User-Agent: 
      - OAuth gem v0.4.6
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Etag: 
      - "\"638fd15ce62b3e067ba639fdfbf34b74\""
      Transfer-Encoding: 
      - chunked
      Content-Type: 
      - application/json; charset=utf-8
      Cache-Control: 
      - max-age=0, private, must-revalidate
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Date: 
      - Mon, 20 Aug 2012 14:19:42 GMT
      X-Runtime: 
      - "0.148882"
    body: 
      string: Deleted environment '131'
    http_version: 
  recorded_at: Mon, 20 Aug 2012 14:19:43 GMT
