--- 
recorded_with: VCR 2.2.4
http_interactions: 
- request: 
    method: post
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments?name=Test&organization_id=ACME_Corporation&prior=1
    body: 
      string: "{\"environment\":{\"name\":\"Test\",\"prior\":1}}"
    headers: 
      Content-Length: 
      - "41"
      Accept: 
      - "*/*"
      Authorization: 
      - OAuth oauth_body_hash="lCe2lMYXISkHQNPzaGPJ0yiK97Y%3D", oauth_consumer_key="cloud_forms", oauth_nonce="RN344lL9UDtVJ4qyHFWPF9l3MA5Os6C6kfLfn3QI1o", oauth_signature="hLvcRDTUCC1czY5W48z4xsP1UFI%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345128411", oauth_version="1.0"
      User-Agent: 
      - OAuth gem v0.4.6
      Content-Type: 
      - application/json
      Http-Katello-User: 
      - admin
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Date: 
      - Thu, 16 Aug 2012 14:46:50 GMT
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Etag: 
      - "\"7ee8e7c615044529015421b35ad707a9\""
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Content-Type: 
      - application/json; charset=utf-8
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      X-Runtime: 
      - "0.373931"
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Transfer-Encoding: 
      - chunked
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":115,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-16T14:46:50Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-16T14:46:50Z\"}"
    http_version: 
  recorded_at: Thu, 16 Aug 2012 14:46:51 GMT
- request: 
    method: get
    uri: https://10.11.230.105/katello/api/environments/115
    body: 
      string: ""
    headers: 
      Accept: 
      - application/json
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="fkHzW8bGrpU2hPGWm4KKMSvunU0cO6IxFQgL3FpGlhU", oauth_signature="ILkKiqxDwrflGKXqCRhMb%2BYdqLA%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345128411", oauth_version="1.0"
      User-Agent: 
      - OAuth gem v0.4.6
      Http-Katello-User: 
      - admin
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Date: 
      - Thu, 16 Aug 2012 14:46:50 GMT
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Etag: 
      - "\"7ee8e7c615044529015421b35ad707a9\""
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Content-Type: 
      - application/json; charset=utf-8
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      X-Runtime: 
      - "0.022883"
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Transfer-Encoding: 
      - chunked
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":115,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-16T14:46:50Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-16T14:46:50Z\"}"
    http_version: 
  recorded_at: Thu, 16 Aug 2012 14:46:51 GMT
- request: 
    method: delete
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments/115
    body: 
      string: ""
    headers: 
      Accept: 
      - application/json
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="KDflbADVOHqQhsrU5pZOvEQvvzUy0DZLZPG1RKns8", oauth_signature="fcmRQIVKt6z%2Bx8GW3uEiM08CUF8%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345128411", oauth_version="1.0"
      User-Agent: 
      - OAuth gem v0.4.6
      Http-Katello-User: 
      - admin
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Date: 
      - Thu, 16 Aug 2012 14:46:50 GMT
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Etag: 
      - "\"62e69a72123b4cd9fe6d3cf1f0939b93\""
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Content-Type: 
      - application/json; charset=utf-8
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      X-Runtime: 
      - "0.138570"
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Transfer-Encoding: 
      - chunked
    body: 
      string: Deleted environment '115'
    http_version: 
  recorded_at: Thu, 16 Aug 2012 14:46:51 GMT
