--- 
http_interactions: 
- request: 
    method: post
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments?name=Test&organization_id=ACME_Corporation&prior=1
    body: 
      string: "{\"environment\":{\"name\":\"Test\",\"prior\":1}}"
    headers: 
      Content-Length: 
      - "41"
      Content-Type: 
      - application/json
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Authorization: 
      - OAuth oauth_body_hash="lCe2lMYXISkHQNPzaGPJ0yiK97Y%3D", oauth_consumer_key="cloud_forms", oauth_nonce="CYrSvSXQYvhhfSAdBoZx7elKuKUVtZbP1p2cyOC5BjA", oauth_signature="Hp3N5OdbDRA75aNHLsluzfnhwnU%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345486924", oauth_version="1.0"
      Accept: 
      - "*/*"
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Content-Type: 
      - application/json; charset=utf-8
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Etag: 
      - "\"69810eb6c256f2ca52fb138afec81cb8\""
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      X-Runtime: 
      - "0.262425"
      Transfer-Encoding: 
      - chunked
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Date: 
      - Mon, 20 Aug 2012 18:22:03 GMT
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":160,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-20T18:22:03Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-20T18:22:03Z\"}"
    http_version: 
  recorded_at: Mon, 20 Aug 2012 18:22:04 GMT
- request: 
    method: get
    uri: https://10.11.230.105/katello/api/environments/160
    body: 
      string: ""
    headers: 
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="uLiaDGvpvXvkmOIqHyk4jpHt5NT4ZUtmRJCXhRVwoBE", oauth_signature="jkDdpKM%2B1A3CPG%2BaF1KbKshauLg%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345486924", oauth_version="1.0"
      Accept: 
      - application/json
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Content-Type: 
      - application/json; charset=utf-8
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Etag: 
      - "\"69810eb6c256f2ca52fb138afec81cb8\""
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      X-Runtime: 
      - "0.022776"
      Transfer-Encoding: 
      - chunked
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Date: 
      - Mon, 20 Aug 2012 18:22:04 GMT
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":160,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-20T18:22:03Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-20T18:22:03Z\"}"
    http_version: 
  recorded_at: Mon, 20 Aug 2012 18:22:05 GMT
- request: 
    method: delete
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments/160
    body: 
      string: ""
    headers: 
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="KDFgGiI8NG9aj90OoHfg096oF25X5oK8wKQiotLxcW0", oauth_signature="UDMn75R6zVoDQqPjx7ejDJ8jjfs%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345486925", oauth_version="1.0"
      Accept: 
      - application/json
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Content-Type: 
      - application/json; charset=utf-8
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Etag: 
      - "\"b1d4058aa0356d1d1e4136904362e877\""
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      X-Runtime: 
      - "0.259419"
      Transfer-Encoding: 
      - chunked
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Date: 
      - Mon, 20 Aug 2012 18:22:04 GMT
    body: 
      string: Deleted environment '160'
    http_version: 
  recorded_at: Mon, 20 Aug 2012 18:22:05 GMT
recorded_with: VCR 2.2.4
