--- 
http_interactions: 
- request: 
    method: post
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments?name=Test&organization_id=ACME_Corporation&prior=1
    body: 
      string: "{\"environment\":{\"name\":\"Test\",\"prior\":1}}"
    headers: 
      Authorization: 
      - OAuth oauth_body_hash="lCe2lMYXISkHQNPzaGPJ0yiK97Y%3D", oauth_consumer_key="cloud_forms", oauth_nonce="WCuCoXJIcQk5X3XW7YqeL68D9GyuxThtZQqACPvWVI0", oauth_signature="e8ESLBctL7cTplwTAiqR6RBe%2BSQ%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1343842700", oauth_version="1.0"
      Accept: 
      - "*/*"
      Http-Katello-User: 
      - admin
      Content-Type: 
      - application/json
      Content-Length: 
      - "41"
      User-Agent: 
      - OAuth gem v0.4.6
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Etag: 
      - "\"c264a876389d8118f1aa0cbc3bd8a398\""
      X-Runtime: 
      - "0.795202"
      Content-Type: 
      - application/json; charset=utf-8
      Date: 
      - Wed, 15 Aug 2012 17:28:46 GMT
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Transfer-Encoding: 
      - chunked
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":102,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-15T17:28:46Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-15T17:28:46Z\"}"
    http_version: 
  recorded_at: Wed, 01 Aug 2012 17:38:20 GMT
- request: 
    method: get
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments
    body: 
      string: ""
    headers: 
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="UMNgZLOv3VrcGpE9rWzpzIFq7Q2waPOYXsNr78ey79w", oauth_signature="yfMooVFepcf5fwepQL1WkekXV2A%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1343842700", oauth_version="1.0"
      Accept: 
      - application/json
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Etag: 
      - "\"c393efd99f87e063a3e3cf8bdd5b448d\""
      X-Runtime: 
      - "0.021937"
      Content-Type: 
      - application/json; charset=utf-8
      Date: 
      - Wed, 15 Aug 2012 17:28:47 GMT
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Transfer-Encoding: 
      - chunked
    body: 
      string: "[{\"library\":true,\"prior\":null,\"id\":1,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-07-02T18:47:39Z\",\"name\":\"Library\",\"description\":null,\"prior_id\":null,\"created_at\":\"2012-07-02T18:47:39Z\"},{\"library\":false,\"prior\":\"Library\",\"id\":102,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-15T17:28:46Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-15T17:28:46Z\"}]"
    http_version: 
  recorded_at: Wed, 01 Aug 2012 17:38:21 GMT
- request: 
    method: delete
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments/102
    body: 
      string: ""
    headers: 
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="3TT4P9MXrRq88hIQJH682CRGtfBCrHSD95h4rVo9XeI", oauth_signature="qsXRgDyWaeyjvyT6rwLT0J0Gjsg%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1343842701", oauth_version="1.0"
      Accept: 
      - application/json
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Etag: 
      - "\"d2a273bb8fccb1af4d369e1bcb29dddb\""
      X-Runtime: 
      - "0.259122"
      Content-Type: 
      - application/json; charset=utf-8
      Date: 
      - Wed, 15 Aug 2012 17:28:47 GMT
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Transfer-Encoding: 
      - chunked
    body: 
      string: Deleted environment '102'
    http_version: 
  recorded_at: Wed, 01 Aug 2012 17:38:21 GMT
recorded_with: VCR 2.2.4
