--- 
http_interactions: 
- request: 
    method: post
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments?name=Test&organization_id=ACME_Corporation&prior=1
    body: 
      string: "{\"environment\":{\"name\":\"Test\",\"prior\":1}}"
    headers: 
      Content-Length: 
      - "41"
      Content-Type: 
      - application/json
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Authorization: 
      - OAuth oauth_body_hash="lCe2lMYXISkHQNPzaGPJ0yiK97Y%3D", oauth_consumer_key="cloud_forms", oauth_nonce="PDDq4G4lYSYmXuMdjrCvzBzv4GjXsxlkcGNmMZCUU", oauth_signature="nv%2BPPA3Ozmc1n0uWEbZpEqBfdj4%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1343842700", oauth_version="1.0"
      Accept: 
      - "*/*"
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Content-Type: 
      - application/json; charset=utf-8
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Etag: 
      - "\"5a6f07ddf58277c87aaeda56c621fd0b\""
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      X-Runtime: 
      - "0.357524"
      Transfer-Encoding: 
      - chunked
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Date: 
      - Mon, 20 Aug 2012 18:22:03 GMT
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":159,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-20T18:22:03Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-20T18:22:03Z\"}"
    http_version: 
  recorded_at: Wed, 01 Aug 2012 17:38:20 GMT
- request: 
    method: get
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments
    body: 
      string: ""
    headers: 
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="h2VORR1PUhps4U8bgGZW8iDZYbh1FaHqO6s2OQMTLw", oauth_signature="tRcsksrL084c6HnCkvjErDLzJxU%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1343842700", oauth_version="1.0"
      Accept: 
      - application/json
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Content-Type: 
      - application/json; charset=utf-8
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Etag: 
      - "\"c3c6ea369953366ac895affc6616e960\""
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      X-Runtime: 
      - "0.027213"
      Transfer-Encoding: 
      - chunked
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Date: 
      - Mon, 20 Aug 2012 18:22:03 GMT
    body: 
      string: "[{\"library\":true,\"prior\":null,\"id\":1,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-07-02T18:47:39Z\",\"name\":\"Library\",\"description\":null,\"prior_id\":null,\"created_at\":\"2012-07-02T18:47:39Z\"},{\"library\":false,\"prior\":\"Library\",\"id\":159,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-20T18:22:03Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-20T18:22:03Z\"}]"
    http_version: 
  recorded_at: Wed, 01 Aug 2012 17:38:20 GMT
- request: 
    method: delete
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments/159
    body: 
      string: ""
    headers: 
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="3PJboKTN1b0u6b19Hqb9152jG9pGN0roJzF5yDlJE", oauth_signature="fCzCabpvcoIy6wj%2BozEi%2F1E3IXI%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1343842700", oauth_version="1.0"
      Accept: 
      - application/json
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Content-Type: 
      - application/json; charset=utf-8
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Etag: 
      - "\"bf7698f7ecceb6a3646356181c5fd763\""
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      X-Runtime: 
      - "0.126697"
      Transfer-Encoding: 
      - chunked
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Date: 
      - Mon, 20 Aug 2012 18:22:03 GMT
    body: 
      string: Deleted environment '159'
    http_version: 
  recorded_at: Wed, 01 Aug 2012 17:38:20 GMT
recorded_with: VCR 2.2.4
