--- 
recorded_with: VCR 2.2.4
http_interactions: 
- request: 
    method: post
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments?name=Test&organization_id=ACME_Corporation&prior=1
    body: 
      string: "{\"environment\":{\"name\":\"Test\",\"prior\":1}}"
    headers: 
      Http-Katello-User: 
      - admin
      Content-Type: 
      - application/json
      Content-Length: 
      - "41"
      Authorization: 
      - OAuth oauth_body_hash="lCe2lMYXISkHQNPzaGPJ0yiK97Y%3D", oauth_consumer_key="cloud_forms", oauth_nonce="pnKLUb1ZlKKCjomc4OBR1N6mZno5YZAzxtgKH8uyBA", oauth_signature="a51RowVywR3VeMFcHUG0%2FPSF9rA%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1343842700", oauth_version="1.0"
      Accept: 
      - "*/*"
      User-Agent: 
      - OAuth gem v0.4.6
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Etag: 
      - "\"a89d423ed5eaaf9cea5f28ebfd0624e9\""
      Transfer-Encoding: 
      - chunked
      Content-Type: 
      - application/json; charset=utf-8
      Cache-Control: 
      - max-age=0, private, must-revalidate
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Date: 
      - Mon, 20 Aug 2012 14:19:41 GMT
      X-Runtime: 
      - "0.349803"
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":130,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-20T14:19:41Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-20T14:19:41Z\"}"
    http_version: 
  recorded_at: Wed, 01 Aug 2012 17:38:20 GMT
- request: 
    method: get
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments
    body: 
      string: ""
    headers: 
      Http-Katello-User: 
      - admin
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="tfzNuQ6LQotnFzbcJFsNUG1iKyBH1IudK7Z9x7iRjs", oauth_signature="1fHuTZf0ntnFuANnaoDOL0Sk4eM%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1343842700", oauth_version="1.0"
      Accept: 
      - application/json
      User-Agent: 
      - OAuth gem v0.4.6
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Etag: 
      - "\"1c7a4343d1b950ad644c43e47e6a3456\""
      Transfer-Encoding: 
      - chunked
      Content-Type: 
      - application/json; charset=utf-8
      Cache-Control: 
      - max-age=0, private, must-revalidate
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Date: 
      - Mon, 20 Aug 2012 14:19:41 GMT
      X-Runtime: 
      - "0.025623"
    body: 
      string: "[{\"library\":true,\"prior\":null,\"id\":1,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-07-02T18:47:39Z\",\"name\":\"Library\",\"description\":null,\"prior_id\":null,\"created_at\":\"2012-07-02T18:47:39Z\"},{\"library\":false,\"prior\":\"Library\",\"id\":130,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-20T14:19:41Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-20T14:19:41Z\"}]"
    http_version: 
  recorded_at: Wed, 01 Aug 2012 17:38:20 GMT
- request: 
    method: delete
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments/130
    body: 
      string: ""
    headers: 
      Http-Katello-User: 
      - admin
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="DtTVUOoY98j9GDs2qxACemmig4oVFZYtW6HLeGtuw", oauth_signature="V8Tg61x%2B4ZWeBbcOJrdHkrMy5d8%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1343842700", oauth_version="1.0"
      Accept: 
      - application/json
      User-Agent: 
      - OAuth gem v0.4.6
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Etag: 
      - "\"cfd381524cb2df57714841e44989dfa4\""
      Transfer-Encoding: 
      - chunked
      Content-Type: 
      - application/json; charset=utf-8
      Cache-Control: 
      - max-age=0, private, must-revalidate
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Date: 
      - Mon, 20 Aug 2012 14:19:41 GMT
      X-Runtime: 
      - "0.140128"
    body: 
      string: Deleted environment '130'
    http_version: 
  recorded_at: Wed, 01 Aug 2012 17:38:20 GMT
