--- 
recorded_with: VCR 2.2.4
http_interactions: 
- request: 
    method: post
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments?name=Test&organization_id=ACME_Corporation&prior=1
    body: 
      string: "{\"environment\":{\"prior\":1,\"name\":\"Test\"}}"
    headers: 
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Authorization: 
      - OAuth oauth_body_hash="9KzQFg2PcGFImVLKB3ygN4CtBaU%3D", oauth_consumer_key="cloud_forms", oauth_nonce="kg9qnAyHTba9AuVcxYJ16WjNug4qDmIaopEUq61oDU", oauth_signature="9OD5uR0KK25mQRXWmtTC%2BhonwiQ%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1343842700", oauth_version="1.0"
      Content-Length: 
      - "41"
      Content-Type: 
      - application/json
      Accept: 
      - "*/*"
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Cache-Control: 
      - max-age=0, private, must-revalidate
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Date: 
      - Wed, 15 Aug 2012 18:46:49 GMT
      Transfer-Encoding: 
      - chunked
      Content-Type: 
      - application/json; charset=utf-8
      X-Runtime: 
      - "0.356907"
      Etag: 
      - "\"3f129f6d848445650fa6e52bf131b3f6\""
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":108,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-15T18:46:49Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-15T18:46:49Z\"}"
    http_version: 
  recorded_at: Wed, 01 Aug 2012 17:38:20 GMT
- request: 
    method: get
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments
    body: 
      string: ""
    headers: 
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="5SVw5ppJorzOZSGoQAbybtchWHhctmeRyHXrFJWbg", oauth_signature="bkyvrTqTzBQH0LIzC4M6EZ1BOr0%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1343842700", oauth_version="1.0"
      Accept: 
      - application/json
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Cache-Control: 
      - max-age=0, private, must-revalidate
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Date: 
      - Wed, 15 Aug 2012 18:46:49 GMT
      Transfer-Encoding: 
      - chunked
      Content-Type: 
      - application/json; charset=utf-8
      X-Runtime: 
      - "0.024701"
      Etag: 
      - "\"67bedea6cfe4bc9bfcb5eefdd32065a5\""
    body: 
      string: "[{\"library\":true,\"prior\":null,\"id\":1,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-07-02T18:47:39Z\",\"name\":\"Library\",\"description\":null,\"prior_id\":null,\"created_at\":\"2012-07-02T18:47:39Z\"},{\"library\":false,\"prior\":\"Library\",\"id\":108,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-15T18:46:49Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-15T18:46:49Z\"}]"
    http_version: 
  recorded_at: Wed, 01 Aug 2012 17:38:20 GMT
- request: 
    method: delete
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments/108
    body: 
      string: ""
    headers: 
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="2pESBrTmVmO5Hz4TWwkqWaxjjCD2DmHxWYfVajAFd60", oauth_signature="BvPI%2BXQYw2TPZO6NLNu%2FywEBO4k%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1343842700", oauth_version="1.0"
      Accept: 
      - application/json
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Cache-Control: 
      - max-age=0, private, must-revalidate
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Date: 
      - Wed, 15 Aug 2012 18:46:49 GMT
      Transfer-Encoding: 
      - chunked
      Content-Type: 
      - application/json; charset=utf-8
      X-Runtime: 
      - "0.144792"
      Etag: 
      - "\"b1b0ac09deb6bf65806e60f01cd17bca\""
    body: 
      string: Deleted environment '108'
    http_version: 
  recorded_at: Wed, 01 Aug 2012 17:38:20 GMT
