--- 
recorded_with: VCR 2.2.4
http_interactions: 
- request: 
    method: post
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments?name=Test&organization_id=ACME_Corporation&prior=1
    body: 
      string: "{\"environment\":{\"prior\":1,\"name\":\"Test\"}}"
    headers: 
      Authorization: 
      - OAuth oauth_body_hash="9KzQFg2PcGFImVLKB3ygN4CtBaU%3D", oauth_consumer_key="cloud_forms", oauth_nonce="oLdjBzgw7zaGerbHVt7gpfkaGJYr806Hv6GYLsd1CE", oauth_signature="ZoystJpF9OTowcu59EU08hIOZq0%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345484825", oauth_version="1.0"
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Accept: 
      - "*/*"
      Content-Length: 
      - "41"
      Content-Type: 
      - application/json
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Date: 
      - Mon, 20 Aug 2012 17:47:04 GMT
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Transfer-Encoding: 
      - chunked
      Content-Type: 
      - application/json; charset=utf-8
      Etag: 
      - "\"ac14f7a70739e1c9c174dff1eef20b87\""
      X-Runtime: 
      - "0.255313"
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":155,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-20T17:47:04Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-20T17:47:04Z\"}"
    http_version: 
  recorded_at: Mon, 20 Aug 2012 17:47:05 GMT
- request: 
    method: get
    uri: https://10.11.230.105/katello/api/environments/155
    body: 
      string: ""
    headers: 
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="GZLToYl9HGBfIYYl2UPDEt7HByeWbLnHvU7SEywpSdk", oauth_signature="WAR7zVH7hvL0jc7sHW0W1Kxz140%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345484825", oauth_version="1.0"
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Accept: 
      - application/json
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Date: 
      - Mon, 20 Aug 2012 17:47:04 GMT
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Transfer-Encoding: 
      - chunked
      Content-Type: 
      - application/json; charset=utf-8
      Etag: 
      - "\"ac14f7a70739e1c9c174dff1eef20b87\""
      X-Runtime: 
      - "0.023396"
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":155,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-20T17:47:04Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-20T17:47:04Z\"}"
    http_version: 
  recorded_at: Mon, 20 Aug 2012 17:47:05 GMT
- request: 
    method: put
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments/155
    body: 
      string: "{\"environment\":{\"description\":\"Test update\"}}"
    headers: 
      Authorization: 
      - OAuth oauth_body_hash="bkfzvOXIr6lM727J5E2JLwc4Z0U%3D", oauth_consumer_key="cloud_forms", oauth_nonce="vV6rfgKxo1NivoLm8YHgUjgMp9nhzKLyPJo957Mup7g", oauth_signature="hLexr5Odd5Yxh5GvgsiagOmu%2FDc%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345484825", oauth_version="1.0"
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Accept: 
      - "*/*"
      Content-Length: 
      - "45"
      Content-Type: 
      - application/json
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Date: 
      - Mon, 20 Aug 2012 17:47:04 GMT
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Transfer-Encoding: 
      - chunked
      Content-Type: 
      - application/json; charset=utf-8
      Etag: 
      - "\"e7cd4d3a8118e2bbed89927123205b4f\""
      X-Runtime: 
      - "0.046574"
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":155,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-20T17:47:04Z\",\"name\":\"Test\",\"description\":\"Test update\",\"prior_id\":1,\"created_at\":\"2012-08-20T17:47:04Z\"}"
    http_version: 
  recorded_at: Mon, 20 Aug 2012 17:47:05 GMT
- request: 
    method: get
    uri: https://10.11.230.105/katello/api/environments/155
    body: 
      string: ""
    headers: 
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="gdalQAOdIxmkXNjWTAWF7MQbYbUNDW90by5KaYWinnk", oauth_signature="Aii%2B3FwwHZPiOYJ9%2BnHn4xzDTJg%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345484825", oauth_version="1.0"
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Accept: 
      - application/json
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Date: 
      - Mon, 20 Aug 2012 17:47:04 GMT
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Transfer-Encoding: 
      - chunked
      Content-Type: 
      - application/json; charset=utf-8
      Etag: 
      - "\"e7cd4d3a8118e2bbed89927123205b4f\""
      X-Runtime: 
      - "0.142569"
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":155,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-20T17:47:04Z\",\"name\":\"Test\",\"description\":\"Test update\",\"prior_id\":1,\"created_at\":\"2012-08-20T17:47:04Z\"}"
    http_version: 
  recorded_at: Mon, 20 Aug 2012 17:47:05 GMT
- request: 
    method: delete
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments/155
    body: 
      string: ""
    headers: 
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="pLWtJlp5FlfGQAMRyXUFEpDGIvHNKYYGYz459rMisyc", oauth_signature="a4PrLonBdbRykujRZPWo8%2FrLvFE%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345484825", oauth_version="1.0"
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Accept: 
      - application/json
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Date: 
      - Mon, 20 Aug 2012 17:47:05 GMT
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Transfer-Encoding: 
      - chunked
      Content-Type: 
      - application/json; charset=utf-8
      Etag: 
      - "\"fe3d11c961f0c734accd81d29d0aa516\""
      X-Runtime: 
      - "0.142647"
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
    body: 
      string: Deleted environment '155'
    http_version: 
  recorded_at: Mon, 20 Aug 2012 17:47:06 GMT
