--- 
recorded_with: VCR 2.2.4
http_interactions: 
- request: 
    method: post
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments?name=Test&organization_id=ACME_Corporation&prior=1
    body: 
      string: "{\"environment\":{\"name\":\"Test\",\"prior\":1}}"
    headers: 
      Http-Katello-User: 
      - admin
      Content-Type: 
      - application/json
      Content-Length: 
      - "41"
      Authorization: 
      - OAuth oauth_body_hash="lCe2lMYXISkHQNPzaGPJ0yiK97Y%3D", oauth_consumer_key="cloud_forms", oauth_nonce="yDT32yMrBxsvuiL9B6awbr6pPwlzTvgl2b67J8nJrU", oauth_signature="Sno8pcDZH%2FPL%2BXy5OieUsKJL9hQ%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345472383", oauth_version="1.0"
      Accept: 
      - "*/*"
      User-Agent: 
      - OAuth gem v0.4.6
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Etag: 
      - "\"295d5d14192d78cbdbebd7512e420e15\""
      Transfer-Encoding: 
      - chunked
      Content-Type: 
      - application/json; charset=utf-8
      Cache-Control: 
      - max-age=0, private, must-revalidate
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Date: 
      - Mon, 20 Aug 2012 14:19:42 GMT
      X-Runtime: 
      - "0.232130"
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":132,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-20T14:19:42Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-20T14:19:42Z\"}"
    http_version: 
  recorded_at: Mon, 20 Aug 2012 14:19:43 GMT
- request: 
    method: get
    uri: https://10.11.230.105/katello/api/environments/132
    body: 
      string: ""
    headers: 
      Http-Katello-User: 
      - admin
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="bTKIRzAIsKjSkjlwLrpZP6yK4lrZ96TLAYoeMRbw", oauth_signature="F9E0XQ8y2whCt7g4tWuUneC0Rio%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345472383", oauth_version="1.0"
      Accept: 
      - application/json
      User-Agent: 
      - OAuth gem v0.4.6
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Etag: 
      - "\"295d5d14192d78cbdbebd7512e420e15\""
      Transfer-Encoding: 
      - chunked
      Content-Type: 
      - application/json; charset=utf-8
      Cache-Control: 
      - max-age=0, private, must-revalidate
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Date: 
      - Mon, 20 Aug 2012 14:19:42 GMT
      X-Runtime: 
      - "0.026095"
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":132,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-20T14:19:42Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-20T14:19:42Z\"}"
    http_version: 
  recorded_at: Mon, 20 Aug 2012 14:19:43 GMT
- request: 
    method: put
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments/132
    body: 
      string: "{\"environment\":{\"description\":\"Test update\"}}"
    headers: 
      Http-Katello-User: 
      - admin
      Content-Type: 
      - application/json
      Content-Length: 
      - "45"
      Authorization: 
      - OAuth oauth_body_hash="bkfzvOXIr6lM727J5E2JLwc4Z0U%3D", oauth_consumer_key="cloud_forms", oauth_nonce="3XlsOvjq4s4QPSr2w7D6ViNdaqI2WV2JBy8hVAaEA", oauth_signature="JBPvGTYQoiC3PdZUNtjHdBA6Er0%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345472383", oauth_version="1.0"
      Accept: 
      - "*/*"
      User-Agent: 
      - OAuth gem v0.4.6
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Etag: 
      - "\"b610696cbfa73449c4782d9d225444c7\""
      Transfer-Encoding: 
      - chunked
      Content-Type: 
      - application/json; charset=utf-8
      Cache-Control: 
      - max-age=0, private, must-revalidate
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Date: 
      - Mon, 20 Aug 2012 14:19:42 GMT
      X-Runtime: 
      - "0.069039"
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":132,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-20T14:19:43Z\",\"name\":\"Test\",\"description\":\"Test update\",\"prior_id\":1,\"created_at\":\"2012-08-20T14:19:42Z\"}"
    http_version: 
  recorded_at: Mon, 20 Aug 2012 14:19:43 GMT
- request: 
    method: get
    uri: https://10.11.230.105/katello/api/environments/132
    body: 
      string: ""
    headers: 
      Http-Katello-User: 
      - admin
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="SFeTjRCTOkC7r0pEaknmgoSJhW5g8exfv1LBcJ7p0", oauth_signature="DRmZseM1jFB5xjW6aBhF0RPrZZk%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345472383", oauth_version="1.0"
      Accept: 
      - application/json
      User-Agent: 
      - OAuth gem v0.4.6
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Etag: 
      - "\"b610696cbfa73449c4782d9d225444c7\""
      Transfer-Encoding: 
      - chunked
      Content-Type: 
      - application/json; charset=utf-8
      Cache-Control: 
      - max-age=0, private, must-revalidate
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Date: 
      - Mon, 20 Aug 2012 14:19:43 GMT
      X-Runtime: 
      - "0.181696"
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":132,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-20T14:19:43Z\",\"name\":\"Test\",\"description\":\"Test update\",\"prior_id\":1,\"created_at\":\"2012-08-20T14:19:42Z\"}"
    http_version: 
  recorded_at: Mon, 20 Aug 2012 14:19:44 GMT
- request: 
    method: delete
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments/132
    body: 
      string: ""
    headers: 
      Http-Katello-User: 
      - admin
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="245PSwnDGtIhQ3PZ7tldNozWrBQ4chHAwCKQ1bNZxGE", oauth_signature="Awwr%2BoVQHvj1dobPRuzcibdSum4%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345472384", oauth_version="1.0"
      Accept: 
      - application/json
      User-Agent: 
      - OAuth gem v0.4.6
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Etag: 
      - "\"b6581b6342d8af22532a77243e09dde9\""
      Transfer-Encoding: 
      - chunked
      Content-Type: 
      - application/json; charset=utf-8
      Cache-Control: 
      - max-age=0, private, must-revalidate
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Date: 
      - Mon, 20 Aug 2012 14:19:43 GMT
      X-Runtime: 
      - "0.179226"
    body: 
      string: Deleted environment '132'
    http_version: 
  recorded_at: Mon, 20 Aug 2012 14:19:44 GMT
