--- 
http_interactions: 
- request: 
    method: post
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments?name=Test&organization_id=ACME_Corporation&prior=1
    body: 
      string: "{\"environment\":{\"name\":\"Test\",\"prior\":1}}"
    headers: 
      Content-Length: 
      - "41"
      Content-Type: 
      - application/json
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Authorization: 
      - OAuth oauth_body_hash="lCe2lMYXISkHQNPzaGPJ0yiK97Y%3D", oauth_consumer_key="cloud_forms", oauth_nonce="7V29zz1CdIUk3QuqjQ1cHGdASKGStDg7mZJF1q5w", oauth_signature="cUtTAtZBtuD%2FnUHHEN4Cu68w%2Brg%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345486925", oauth_version="1.0"
      Accept: 
      - "*/*"
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Content-Type: 
      - application/json; charset=utf-8
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Etag: 
      - "\"26697e0679ceac86c89714afe375150c\""
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      X-Runtime: 
      - "0.256188"
      Transfer-Encoding: 
      - chunked
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Date: 
      - Mon, 20 Aug 2012 18:22:04 GMT
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":161,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-20T18:22:04Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-20T18:22:04Z\"}"
    http_version: 
  recorded_at: Mon, 20 Aug 2012 18:22:05 GMT
- request: 
    method: get
    uri: https://10.11.230.105/katello/api/environments/161
    body: 
      string: ""
    headers: 
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="ZQRaPPVcqwJBfRWzXc5IWDX5NmoAIZpyaBm7ezfoaCk", oauth_signature="XGCo0OPMY%2BdHVywRUgD2vsSWzWQ%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345486925", oauth_version="1.0"
      Accept: 
      - application/json
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Content-Type: 
      - application/json; charset=utf-8
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Etag: 
      - "\"26697e0679ceac86c89714afe375150c\""
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      X-Runtime: 
      - "0.020771"
      Transfer-Encoding: 
      - chunked
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Date: 
      - Mon, 20 Aug 2012 18:22:04 GMT
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":161,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-20T18:22:04Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-20T18:22:04Z\"}"
    http_version: 
  recorded_at: Mon, 20 Aug 2012 18:22:05 GMT
- request: 
    method: put
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments/161
    body: 
      string: "{\"environment\":{\"description\":\"Test update\"}}"
    headers: 
      Content-Length: 
      - "45"
      Content-Type: 
      - application/json
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Authorization: 
      - OAuth oauth_body_hash="bkfzvOXIr6lM727J5E2JLwc4Z0U%3D", oauth_consumer_key="cloud_forms", oauth_nonce="gkshTQ7nRayqiRJsV4G9c3nABdl1Njv6g1Cxc8NBoGg", oauth_signature="7tsl6czES%2F4%2F6I6Oc%2BNgnWhguIQ%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345486925", oauth_version="1.0"
      Accept: 
      - "*/*"
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Content-Type: 
      - application/json; charset=utf-8
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Etag: 
      - "\"57c8c8319c1189f12f7849e61791b127\""
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      X-Runtime: 
      - "0.039845"
      Transfer-Encoding: 
      - chunked
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Date: 
      - Mon, 20 Aug 2012 18:22:04 GMT
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":161,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-20T18:22:05Z\",\"name\":\"Test\",\"description\":\"Test update\",\"prior_id\":1,\"created_at\":\"2012-08-20T18:22:04Z\"}"
    http_version: 
  recorded_at: Mon, 20 Aug 2012 18:22:05 GMT
- request: 
    method: get
    uri: https://10.11.230.105/katello/api/environments/161
    body: 
      string: ""
    headers: 
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="zBc12GRVQyQ1x6Jb5z3tcuYEWWsATN3r6lh4WE", oauth_signature="5x5eF9gKouz5Gq7qELhwscUW9Kg%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345486925", oauth_version="1.0"
      Accept: 
      - application/json
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Content-Type: 
      - application/json; charset=utf-8
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Etag: 
      - "\"57c8c8319c1189f12f7849e61791b127\""
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      X-Runtime: 
      - "0.024076"
      Transfer-Encoding: 
      - chunked
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Date: 
      - Mon, 20 Aug 2012 18:22:05 GMT
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":161,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-20T18:22:05Z\",\"name\":\"Test\",\"description\":\"Test update\",\"prior_id\":1,\"created_at\":\"2012-08-20T18:22:04Z\"}"
    http_version: 
  recorded_at: Mon, 20 Aug 2012 18:22:05 GMT
- request: 
    method: delete
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments/161
    body: 
      string: ""
    headers: 
      Http-Katello-User: 
      - admin
      User-Agent: 
      - OAuth gem v0.4.6
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="Bd8xQxAr2Bv17PJkQpZOFmsSn58bgPjHznctmWROo94", oauth_signature="vSXAMvSDTLVvnRtO62suDotuG5U%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345486925", oauth_version="1.0"
      Accept: 
      - application/json
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
      Content-Type: 
      - application/json; charset=utf-8
      Cache-Control: 
      - max-age=0, private, must-revalidate
      Etag: 
      - "\"fd1d8f5924017a7278efe885ea4bfb88\""
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      X-Runtime: 
      - "0.267177"
      Transfer-Encoding: 
      - chunked
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Date: 
      - Mon, 20 Aug 2012 18:22:05 GMT
    body: 
      string: Deleted environment '161'
    http_version: 
  recorded_at: Mon, 20 Aug 2012 18:22:06 GMT
recorded_with: VCR 2.2.4
