--- 
http_interactions: 
- request: 
    method: post
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments?name=Test&organization_id=ACME_Corporation&prior=1
    body: 
      string: "{\"environment\":{\"name\":\"Test\",\"prior\":1}}"
    headers: 
      Content-Type: 
      - application/json
      Content-Length: 
      - "41"
      User-Agent: 
      - OAuth gem v0.4.6
      Authorization: 
      - OAuth oauth_body_hash="lCe2lMYXISkHQNPzaGPJ0yiK97Y%3D", oauth_consumer_key="cloud_forms", oauth_nonce="AL91swXT7npaHLXh8rSL5wcic5OMFVzIUsc6bOHIM", oauth_signature="MdBdFOip55U3YprDsSjPe621D%2BE%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345645395", oauth_version="1.0"
      Accept: 
      - "*/*"
      Http-Katello-User: 
      - admin
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Content-Type: 
      - application/json; charset=utf-8
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Transfer-Encoding: 
      - chunked
      Date: 
      - Wed, 22 Aug 2012 14:23:15 GMT
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Cache-Control: 
      - max-age=0, private, must-revalidate
      X-Runtime: 
      - "0.388882"
      Etag: 
      - "\"3e32537a496a7e01ef8b9c77a77dc1cd\""
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":199,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-22T14:23:15Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-22T14:23:15Z\"}"
    http_version: 
  recorded_at: Wed, 22 Aug 2012 14:23:16 GMT
- request: 
    method: get
    uri: https://10.11.230.105/katello/api/environments/199
    body: 
      string: ""
    headers: 
      User-Agent: 
      - OAuth gem v0.4.6
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="pie4k66jIuvxHLrK16FDPtd19fraXbhAxMkZCVm5Is", oauth_signature="ZkqXrrNoxVHUorIVGA9VzYs3fgU%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345645396", oauth_version="1.0"
      Accept: 
      - application/json
      Http-Katello-User: 
      - admin
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Content-Type: 
      - application/json; charset=utf-8
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Transfer-Encoding: 
      - chunked
      Date: 
      - Wed, 22 Aug 2012 14:23:15 GMT
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Cache-Control: 
      - max-age=0, private, must-revalidate
      X-Runtime: 
      - "0.020008"
      Etag: 
      - "\"3e32537a496a7e01ef8b9c77a77dc1cd\""
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":199,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-22T14:23:15Z\",\"name\":\"Test\",\"description\":null,\"prior_id\":1,\"created_at\":\"2012-08-22T14:23:15Z\"}"
    http_version: 
  recorded_at: Wed, 22 Aug 2012 14:23:16 GMT
- request: 
    method: put
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments/199
    body: 
      string: "{\"environment\":{\"description\":\"Test update\"}}"
    headers: 
      Content-Type: 
      - application/json
      Content-Length: 
      - "45"
      User-Agent: 
      - OAuth gem v0.4.6
      Authorization: 
      - OAuth oauth_body_hash="bkfzvOXIr6lM727J5E2JLwc4Z0U%3D", oauth_consumer_key="cloud_forms", oauth_nonce="9XV89FJlWDsm2ID9vnd4gqKMPwUHINjVhvl5CLD00dk", oauth_signature="jnDDWDKzUvJ0nHGqzDLVGbXjjeY%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345645396", oauth_version="1.0"
      Accept: 
      - "*/*"
      Http-Katello-User: 
      - admin
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Content-Type: 
      - application/json; charset=utf-8
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Transfer-Encoding: 
      - chunked
      Date: 
      - Wed, 22 Aug 2012 14:23:15 GMT
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Cache-Control: 
      - max-age=0, private, must-revalidate
      X-Runtime: 
      - "0.051278"
      Etag: 
      - "\"425227ed646bf20873f0e242965f90ce\""
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":199,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-22T14:23:15Z\",\"name\":\"Test\",\"description\":\"Test update\",\"prior_id\":1,\"created_at\":\"2012-08-22T14:23:15Z\"}"
    http_version: 
  recorded_at: Wed, 22 Aug 2012 14:23:16 GMT
- request: 
    method: get
    uri: https://10.11.230.105/katello/api/environments/199
    body: 
      string: ""
    headers: 
      User-Agent: 
      - OAuth gem v0.4.6
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="7roq48SZRFsBzLZojmMCtjkwRgUVgaI887NAWBfruI", oauth_signature="6XD7LS6uw570r5Wk7VT4xhAL5NQ%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345645396", oauth_version="1.0"
      Accept: 
      - application/json
      Http-Katello-User: 
      - admin
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Content-Type: 
      - application/json; charset=utf-8
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Transfer-Encoding: 
      - chunked
      Date: 
      - Wed, 22 Aug 2012 14:23:15 GMT
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Cache-Control: 
      - max-age=0, private, must-revalidate
      X-Runtime: 
      - "0.019871"
      Etag: 
      - "\"425227ed646bf20873f0e242965f90ce\""
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
    body: 
      string: "{\"library\":false,\"prior\":\"Library\",\"id\":199,\"organization\":\"ACME_Corporation\",\"organization_id\":1,\"updated_at\":\"2012-08-22T14:23:15Z\",\"name\":\"Test\",\"description\":\"Test update\",\"prior_id\":1,\"created_at\":\"2012-08-22T14:23:15Z\"}"
    http_version: 
  recorded_at: Wed, 22 Aug 2012 14:23:16 GMT
- request: 
    method: delete
    uri: https://10.11.230.105/katello/api/organizations/ACME_Corporation/environments/199
    body: 
      string: ""
    headers: 
      User-Agent: 
      - OAuth gem v0.4.6
      Authorization: 
      - OAuth oauth_consumer_key="cloud_forms", oauth_nonce="4oD5gaj2LvQv09CwpdKAEShtk0PqSUeMNJEeOeuygWg", oauth_signature="DFj8f7XpsnTE%2FzVn6%2BoeUfDzVbU%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1345645396", oauth_version="1.0"
      Accept: 
      - application/json
      Http-Katello-User: 
      - admin
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Content-Type: 
      - application/json; charset=utf-8
      Server: 
      - thin 1.2.11 codename Bat-Shit Crazy
      Transfer-Encoding: 
      - chunked
      Date: 
      - Wed, 22 Aug 2012 14:23:15 GMT
      X-Ua-Compatible: 
      - IE=Edge,chrome=1
      Cache-Control: 
      - max-age=0, private, must-revalidate
      X-Runtime: 
      - "0.123089"
      Etag: 
      - "\"9c123880c0dae45e710ee81a4db6c610\""
      X-Candlepin-Version: 
      - katello/0.2.44-1.el6
    body: 
      string: Deleted environment '199'
    http_version: 
  recorded_at: Wed, 22 Aug 2012 14:23:16 GMT
recorded_with: VCR 2.2.4
